In [1]:
import numpy as np

In [2]:
# Paprastas 1D masyvas (vienos dimensijos)
a = np.array([10, 20, 30, 40])
 
print("a =", a)
print("a.ndim  =", a.ndim)   # dimensijų skaičius
print("a.shape =", a.shape)  # forma
print("a.size  =", a.size)   # elementų kiekis
print("a.dtype =", a.dtype)  # duomenų tipas
 

a = [10 20 30 40]
a.ndim  = 1
a.shape = (4,)
a.size  = 4
a.dtype = int64


In [3]:
# 2D masyvas (dvi dimensijos, dažnai vadinamas matrica)
b = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(b)
print("b =\n", b)
print("b.ndim  =", b.ndim)
print("b.shape =", b.shape)  # 2 eilutės, 3 stulpeliai
print("b.size  =", b.size)   # 2 * 3 = 6 elementai
print("b.dtype =", b.dtype)

[[1 2 3]
 [4 5 6]]
b =
 [[1 2 3]
 [4 5 6]]
b.ndim  = 2
b.shape = (2, 3)
b.size  = 6
b.dtype = int64


In [4]:
x = np.array([5, 10, 15])
y = np.array([[1, 2], [3, 4]])
 
print("x =", x)
print("y =\n", y)
 

x = [ 5 10 15]
y =
 [[1 2]
 [3 4]]


In [5]:
ones_1d = np.ones(5)        # 1D masyvas iš 5 vienetų
ones_2d = np.ones((2, 3))   # 2D masyvas: 2x3
 
print("ones_1d =", ones_1d)
print("ones_2d =\n", ones_2d)
print("ones_2d.dtype =", ones_2d.dtype)
 
zeros_1d = np.zeros(4)
zeros_2d = np.zeros((3, 2))
 
print("zeros_1d =", zeros_1d)
print("zeros_2d =\n", zeros_2d)
 

ones_1d = [1. 1. 1. 1. 1.]
ones_2d =
 [[1. 1. 1.]
 [1. 1. 1.]]
ones_2d.dtype = float64
zeros_1d = [0. 0. 0. 0.]
zeros_2d =
 [[0. 0.]
 [0. 0.]
 [0. 0.]]


In [6]:
np.zeros(3)

array([0., 0., 0.])

In [11]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
np.ones(3)

array([1., 1., 1.])

In [9]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
seq1 = np.arange(0, 10)        # 0, 1, 2, ..., 9
seq2 = np.arange(2, 11, 2)     # 2, 4, 6, 8, 10
 
print("seq1 =", seq1)
print("seq2 =", seq2)

seq1 = [0 1 2 3 4 5 6 7 8 9]
seq2 = [ 2  4  6  8 10]


In [13]:
lin1 = np.linspace(0, 1, 5)      # 5 reikšmės nuo 0 iki 1
lin2 = np.linspace(10, 20, 3)    # 10, 15, 20
 
print("lin1 =", lin1)
print("lin2 =", lin2)
 

lin1 = [0.   0.25 0.5  0.75 1.  ]
lin2 = [10. 15. 20.]


In [14]:
# Pradinis 1D masyvas su 6 elementais
r = np.arange(1, 7)   # [1, 2, 3, 4, 5, 6]
 
print("r =", r)
print("r.shape =", r.shape)

r = [1 2 3 4 5 6]
r.shape = (6,)


In [15]:
# Formos pakeitimas į 2x3
r_2x3 = r.reshape(2, 3)
 
print("r_2x3 =\n", r_2x3)
print("r_2x3.shape =", r_2x3.shape)

r_2x3 =
 [[1 2 3]
 [4 5 6]]
r_2x3.shape = (2, 3)


In [16]:
a = np.array([10, 20, 30, 40, 50])
 
print("a =", a)
print("a[0]  =", a[0])   # pirmas elementas
print("a[2]  =", a[2])   # trečias elementas
print("a[-1] =", a[-1])  # paskutinis elementas

a = [10 20 30 40 50]
a[0]  = 10
a[2]  = 30
a[-1] = 50


In [17]:
b = np.array([
    [1,  2,  3],
    [4,  5,  6],
    [7,  8,  9]
])
 
print("b =\n", b)
print("b[0, 0] =", b[0, 0])   # 1 (pirma eilutė, pirmas stulpelis)
print("b[1, 2] =", b[1, 2])   # 6 (antra eilutė, trečias stulpelis)
print("b[-1, -1] =", b[-1, -1])  # 9 (paskutinė eilutė, paskutinis stulpelis)

b =
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
b[0, 0] = 1
b[1, 2] = 6
b[-1, -1] = 9


In [18]:
x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
 
print("x =", x)
print("x[2:6] =", x[2:6])      # elementai su indeksais 2,3,4,5
print("x[:4]  =", x[:4])       # nuo pradžios iki 4 (neįtraukiant)
print("x[5:]  =", x[5:])       # nuo 5 iki galo
print("x[::2] =", x[::2])      # kas antras elementas
print("x[::-1] =", x[::-1])    # apsukimas atgaline tvarka

x = [0 1 2 3 4 5 6 7 8 9]
x[2:6] = [2 3 4 5]
x[:4]  = [0 1 2 3]
x[5:]  = [5 6 7 8 9]
x[::2] = [0 2 4 6 8]
x[::-1] = [9 8 7 6 5 4 3 2 1 0]


In [19]:
p = np.array([1, 2, 3, 4])
q = np.array([10, 20, 30, 40])
 
print("p =", p)
print("q =", q)
 
print("p + q =", p + q)     # elementų suma
print("q - p =", q - p)     # elementų skirtumas
print("p * 2 =", p * 2)     # daugyba iš skaičiaus
print("q / 10 =", q / 10)   # dalyba iš skaičiaus (rezultatas dažnai tampa float)

p = [1 2 3 4]
q = [10 20 30 40]
p + q = [11 22 33 44]
q - p = [ 9 18 27 36]
p * 2 = [2 4 6 8]
q / 10 = [1. 2. 3. 4.]


In [20]:
values = np.array([3, 7, 2, 9, 5])
 
print("values =", values)
print("values > 5 =", values > 5)
print("values == 7 =", values == 7)
 
values = np.array([3, 7, 2, 9, 5])
 
mask = values > 5
filtered = values[mask]
 
print("values =", values)
print("mask =", mask)
print("values[mask] =", filtered)
 

values = [3 7 2 9 5]
values > 5 = [False  True False  True False]
values == 7 = [False  True False False False]
values = [3 7 2 9 5]
mask = [False  True False  True False]
values[mask] = [7 9]


In [21]:
values = np.array([3, 7, 2, 9, 5, 8, 1])
 
mask_between = (values >= 3) & (values <= 8)
print("values =", values)
print("mask_between =", mask_between)
print("values[mask_between] =", values[mask_between])

values = [3 7 2 9 5 8 1]
mask_between = [ True  True False False  True  True False]
values[mask_between] = [3 7 5 8]
